Document: grip
Title: Debian grip Manual
Author: <insert document author here>
Abstract: This manual describes what grip is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/grip/grip.sgml.gz

Format: postscript
Files: /usr/share/doc/grip/grip.ps.gz

Format: text
Files: /usr/share/doc/grip/grip.text.gz

Format: HTML
Index: /usr/share/doc/grip/html/index.html
Files: /usr/share/doc/grip/html/*.html
